paths:
  /productsCollection:
    post:
      tags:
        - productsCollection
      summary: Create a new instance of the model and persist it into the data source.
      operationId: productsCollection.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/productsCollection'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/productsCollection'
      deprecated: false
    patch:
      tags:
        - productsCollection
      summary: Patch an existing model instance or insert a new one into the data source.
      operationId: productsCollection.patchOrCreate
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/productsCollection'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/productsCollection'
      deprecated: false
    put:
      tags:
        - productsCollection
      summary: Replace an existing model instance or insert a new one into the data source.
      operationId: productsCollection.replaceOrCreate__put_productsCollection
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/productsCollection'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/productsCollection'
      deprecated: false
    get:
      tags:
        - productsCollection
      summary: Find all instances of the model matched by filter from the data source.
      operationId: productsCollection.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/productsCollection'
      deprecated: false
  /productsCollection/replaceOrCreate:
    post:
      tags:
        - productsCollection
      summary: Replace an existing model instance or insert a new one into the data source.
      operationId: productsCollection.replaceOrCreate__post_productsCollection_replaceOrCreate
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/productsCollection'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/productsCollection'
      deprecated: false
  /productsCollection/upsertWithWhere:
    post:
      tags:
        - productsCollection
      summary: Update an existing model instance or insert a new one into the data source based on the where criteria.
      operationId: productsCollection.upsertWithWhere
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/productsCollection'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/productsCollection'
      deprecated: false
  '/productsCollection/{id}/exists':
    get:
      tags:
        - productsCollection
      summary: Check whether a model instance exists in the data source.
      operationId: 'productsCollection.exists__get_productsCollection_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/productsCollection/{id}':
    head:
      tags:
        - productsCollection
      summary: Check whether a model instance exists in the data source.
      operationId: 'productsCollection.exists__head_productsCollection_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - productsCollection
      summary: 'Find a model instance by {{id}} from the data source.'
      operationId: productsCollection.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: 'Filter defining fields and include - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/productsCollection'
      deprecated: false
    put:
      tags:
        - productsCollection
      summary: Replace attributes for a model instance and persist it into the data source.
      operationId: 'productsCollection.replaceById__put_productsCollection_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/productsCollection'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/productsCollection'
      deprecated: false
    delete:
      tags:
        - productsCollection
      summary: 'Delete a model instance by {{id}} from the data source.'
      operationId: productsCollection.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    patch:
      tags:
        - productsCollection
      summary: Patch attributes for a model instance and persist it into the data source.
      operationId: productsCollection.prototype.patchAttributes
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/productsCollection'
        - name: id
          in: path
          description: productsCollection id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/productsCollection'
      deprecated: false
  '/productsCollection/{id}/replace':
    post:
      tags:
        - productsCollection
      summary: Replace attributes for a model instance and persist it into the data source.
      operationId: 'productsCollection.replaceById__post_productsCollection_{id}_replace'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/productsCollection'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/productsCollection'
      deprecated: false
  /productsCollection/findOne:
    get:
      tags:
        - productsCollection
      summary: Find first instance of the model matched by filter from the data source.
      operationId: productsCollection.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/productsCollection'
      deprecated: false
  /productsCollection/update:
    post:
      tags:
        - productsCollection
      summary: 'Update instances of the model matched by {{where}} from the data source.'
      operationId: productsCollection.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/productsCollection'
      responses:
        '200':
          description: Request was successful
          schema:
            description: Information related to the outcome of the operation
            type: object
            properties:
              count:
                description: The number of instances updated
                type: number
                format: double
      deprecated: false
  /productsCollection/count:
    get:
      tags:
        - productsCollection
      summary: Count instances of the model matched by where from the data source.
      operationId: productsCollection.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
  /Products/search:
    post:
      tags:
        - Product
      operationId: Product.search
      parameters: []
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/x-any'
      deprecated: false
definitions:
  productsCollection:
    properties:
      id:
        $ref: '#/definitions/ObjectID'
    additionalProperties: false
  x-any:
    properties: {}
  ObjectID:
    type: string
    pattern: "^[a-fA-F\\d]{24}$"
basePath: /api
swagger: '2.0'
info:
  x-ibm-name: foodvisbackend
  version: 1.0.0
  title: FoodVisBackend
schemes:
  - https
host: $(catalog.host)
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientIdHeader: []
    clientSecretHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
